#! /usr/bin/env ruby

#
# This Agent uses the passenger commands to track the number of running
# and active passenger processes as well as their memory usage
#

require "rubygems"
require "bundler/setup"

require "newrelic_plugin"

module ExampleAgent

  class Agent < NewRelic::Plugin::Agent::Base

    agent_guid "net.theimp.newrelic-plugin.passenger"
    agent_version "0.0.2"
    #agent_config_options :hertz  # frequency of the periodic functions
    agent_human_labels("Passenger") { "Passenger on #{`hostname`}" }



    def poll_cycle
      
      passenger_status = '/usr/local/bin/passenger-status'

      #Shamelessly copied from https://github.com/barttenbrinke/munin-plugins-rails
      status = run_command(passenger_status)

      status =~ /max\s+=\s+(\d+)/
      report_metric "passenger.processes.max", "Processes", $1
      puts "max.value #{$1}"

      status =~ /count\s+=\s+(\d+)/
      report_metric "passenger.processes.running", "Processes", $1
      puts "running.value #{$1}"

      status =~ /active\s+=\s+(\d+)/
      report_metric "passenger.processes.active", "Processes", $1
      puts "active.value #{$1}"

      status =~ /Waiting on global queue:\s+(\d+)/
      report_metric "passenger.queue.waiting", "Requests", $1
      puts "requests.value #{$1}"

      total_sessions = 0
      status.scan(/Sessions: (\d+)/).flatten.each { |count| total_sessions += count.to_i }
      report_metric "passenger.sessions.total", "Sessions", $1
      puts "sessions.value #{total_sessions}"


      passenger_memory_stats = '/usr/local/bin/passenger-memory-stats'

      stats = run_command(passenger_memory_stats)

      stats =~ /RSS:\s*([\d\.]+)\s*MB\Z/m
      report_metric "passenger.memory.usage", "Megabyte", $1
      puts "memory.value #{memory}"
 
    end

    
    private      

    def run_command(command)
      result = `#{command}`

      unless $?.success?
        $stderr.puts "failed executing #{command}"
        exit 1
      end

      result
    end


  end

  #
  # Register this agent with the component.
  # The ExampleAgent is the name of the module that defines this
  # driver (the module must contain at least three classes - a
  # PollCycle, a Metric and an Agent class, as defined above).
  #
  NewRelic::Plugin::Setup.install_agent :example, ExampleAgent

  #
  # Launch the agent; this never returns.
  #
  NewRelic::Plugin::Run.setup_and_run

end
